---
# tasks file for master
- name: Configuring the kubelet cgroup driver
  template:
     src: kube-config.yml
     dest: /home/{{ k8s_master_user }}/kubeadm-config.yaml 

- name: Configure kubectl
  become: true
  command: kubeadm init --config /home/{{ k8s_master_user }}/kubeadm-config.yaml
  args: 
    creates: /etc/kubernetes/manifests/kube-apiserver.yaml

- name: Create .kube dir for {{ k8s_master_user }} user
  file:
      path: "/home/{{ k8s_master_user }}/.kube"
      state: directory

- name: Copy kube config to {{ k8s_master_user }} home .kube dir 
  copy:
    src: /etc/kubernetes/admin.conf
    dest:  /home/{{ k8s_master_user }}/.kube/config
    remote_src: yes
    owner: "{{ k8s_master_user }}"
    group: "{{ k8s_master_group }}"
    mode: 0660

- name: Rewrite kube-flannel.yaml
  template:
     src: kube-flannel.yml
     dest: /home/{{ k8s_master_user }}/kube-flannel.yaml
    
- name: Install Flannel (using Kubernetes API datastore)
  become: false
  command: kubectl apply -f /home/{{ k8s_master_user }}/kube-flannel.yaml
  
# Step 2.6 from https://kubernetes.io/blog/2019/03/15/kubernetes-setup-using-ansible-and-vagrant/
- name: Generate join command
  command: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command for {{ k8s_cluster_name }} cluster to local file
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./{{ k8s_cluster_name }}-join-command"
