---
- name: Copy bridge config file
  template:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf

- name: Config sysctl
  become: true
  shell: |
    echo 'net.bridge.bridge-nf-call-iptables=1' | tee -a /etc/sysctl.conf
    echo 'net.ipv4.ip_forward=1' | tee -a /etc/sysctl.conf

- name: Reload bridge firewall rule
  become: true
  command: sysctl --system
