---
# tasks file for worker

- name: Copy the join command to {{ k8s_cluster_name }} cluster
  copy: 
    src: "./{{ k8s_cluster_name }}-join-command" 
    dest: "/home/{{ k8s_node_user }}/{{ k8s_cluster_name }}-join-command"
    owner: "{{ k8s_node_user }}"
    group: "{{ k8s_node_group }}"
    mode: 0760  

- name: Join the node to cluster {{ k8s_cluster_name }}
  command: sh /home/{{ k8s_node_user }}/{{ k8s_cluster_name }}-join-command
  ignore_errors: true
