- hosts: '{{ TARGET | default("ec2_master") }}'
  gather_facts: True
  become: True
  become_user: root
  become_method: sudo
  roles:
    - role: v1.16.10/master

- hosts: '{{ TARGET | default("ec2_worker") }}'
  gather_facts: True
  become: True
  become_user: root
  become_method: sudo

  roles:
    - role: v1.16.10/worker
